apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-status
  labels:
    app: nginx-status
    prometheus: default
spec:
  selector:
    matchLabels:
      app: nginx-status
      prometheus: default
  endpoints:
  - port: metrics
