apiVersion: v1
kind: Service
metadata:
  name: nginx-status
  labels:
    app: nginx-status
    prometheus: default
spec:
  selector:
    app: nginx-status
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - protocol: TCP
      port: 9113
      targetPort: 9113
      name: metrics