apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - prod.o-k-hw6.dns-cloud.net
    secretName: echo-tls
  rules:
  - host: prod.o-k-hw6.dns-cloud.net
    http:
      paths:
      - backend:
          serviceName: nginx-ingress-controller
          servicePort: 80
