replicaCount: 3
nodeSelector:
  cloud.google.com/gke-nodepool: infra-pool
tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule
webhook:
  replicaCount: 3
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
cainjector:
  replicaCount: 3
  nodeSelector:
    cloud.google.com/gke-nodepool: infra-pool
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule

